

#models_list
DDEFS           += -DROBOT_DIFF_2WD=1 -DROBOT_DIFF_4WD=2 -DROBOT_OMNI_3=10 -DROBOT_OMNI_4=11 -DROBOT_MECANUM=12

#motor_controller_list
DDEFS           += -DCOMMON_CONTROLLER=1 -DAF_SHIELD_CONTROLLER=2

DDEFS			+= -DMOTOR1_REVERSE=0 -DMOTOR2_REVERSE=0 -DMOTOR3_REVERSE=0 -DMOTOR4_REVERSE=0
DDEFS			+= -DENCODER1_REVERSE=0 -DENCODER2_REVERSE=0 -DENCODER3_REVERSE=0 -DENCODER4_REVERSE=0 
#models
#DDEFS           += -DROBOT_MODEL=ROBOT_DIFF_2WD -DMOTOR_CONTROLLER=COMMON_CONTROLLER
#DDEFS           += -DROBOT_MODEL=ROBOT_DIFF_4WD -DMOTOR_CONTROLLER=COMMON_CONTROLLER
#DDEFS           += -DROBOT_MODEL=ROBOT_OMNI_3 -DMOTOR_CONTROLLER=COMMON_CONTROLLER
DDEFS           += -DROBOT_MODEL=ROBOT_MECANUM -DMOTOR_CONTROLLER=COMMON_CONTROLLER


#com
DDEFS           += -DUSART_DEBUG=USART_2 -DMASTER_USART=USART_0
DDEFS           += -DUSART_DEBUG_BAUD=921600 -DUSART_MASTER_BAUD=921600
DDEFS           += -DIIC_AT24CXX=1

#imu
DDEFS           += -DIIC_GY85=3
DDEFS           += -DIMU_ENABLE=1

#debug
DDEFS           += -DDEBUG_ENABLE=0
DDEFS           += -DODOM_DEBUG_OUTPUT=0
DDEFS           += -DPID_DEBUG_OUTPUT=0
DDEFS           += -DIMU_DEBUG_ENABLE=0
